### ISSUE TITLE
tried to follow directions exactly and got errors i dont know if its even running

### ISSUE THREAD

**Issue by Lg-PWNd** [whasonyt/glitch247#3]
Replit: Updating package configuration

--> npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'glitch247@1.0.0',
npm WARN EBADENGINE   required: { node: '12.x' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }

added 51 packages, and audited 52 packages in 5s

4 high severity vulnerabilities
Error: Cannot find module '/home/runner/node-keepalive/index.js'
Require stack:
- /nix/store/29fdcv1yhlll61ml8a31qdkrbprxd7gs-prybar-nodejs-0.0.0-67f7a00/prybar_assets/nodejs/module-context-hook.js
- /tmp/prybar-nodejs-1584950049.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
Hint: hit control+c anytime to enter REPL.

**Comment by cmdwm** [comment]
This is not a one-size fits all solution. You need to open .replit file and set the start code to whatever the JS file is that package.json points to. Closing this ticket as solved, message me on twitter if you need more help.
